-- React version by @sircfenner
-- Aegis version by @2jammers

local Constants = {}

Constants.DefaultFont = Enum.Font.SourceSans
Constants.DefaultTextSize = 14
Constants.DefaultButtonHeight = 24
Constants.DefaultToggleHeight = 20
Constants.DefaultInputHeight = 22
Constants.DefaultSliderHeight = 22
Constants.DefaultDropdownHeight = 20
Constants.DefaultDropdownRowHeight = 16
Constants.DefaultProgressBarHeight = 14
Constants.DefaultColorPickerSize = UDim2.fromOffset(260, 285)
Constants.DefaultNumberSequencePickerSize = UDim2.fromOffset(425, 285)

return table.freeze(Constants)